"""
Notes on Ape-X DQN:
Ape-X is a distributed reinforcement learning architecture that combines:
1. Prioritized Experience Replay (PER) for prioritized sampling
2. Distributed actors for parallel experience collection
3. Centralized learner for efficient optimization

Key differences from standard DQN:
1. Actors collect experiences in parallel and push them to a shared buffer
2. The learner samples from the shared buffer and updates the network
3. Actors periodically sync weights from the learner
4. N-step returns are used to improve sample efficiency
5. Dueling DQN architecture is used to improve performance

The main goal of the paper was to show that a centralized learner could train agents more efficiently
by leveraging the parallel experience collection of multiple actors. Essentially, it was to reduce wall clock time by having many actors collect data in parallel. There were a few DQN specific changes (like different values of epsilon for each actor) to improve performance. Ape-X also introduced online priority calculation in the actors instead of using the base max priority. By doing this it removes the focus on the most recent data in the buffer, and instead focuses on the most important data in the buffer. This comes at no cost to the learner. To prevent network or IPC (Inter-Process Communication) bottlenecks, actors do not send single transitions to the replay buffer. They batch experience data locally (e.g., chunks of 50 or 100 transitions) and send them asynchronously, drastically reducing the overhead on the centralized server.

The paper also showed that the recency of the data was not the cause of the increased performance, but the quantity and scale of the data was infact the reason for the increased performance.

The Ape-X framework is algorithm-agnostic. The authors proved this by successfully scaling DDPG (Ape-X DPG) for continuous control tasks alongside DQN, showing that the decoupled actor/learner and prioritized replay framework generalizes across discrete and continuous action spaces.

This technique is now standard practice for training deep reinforcement learning agents at scale. AlphaZero, MuZero, and other state of the art algorithms use similar architectures (in terms of distributed actors and a central learner/server). The use of the online priority calculation is less common in other algorithms. In terms of the different values of epsilon, this does not generally apply to algorithms that don't use epsilon greedy, however it could feasibly be applied in some way to other algorithms as well, where each actor is assigned a different exploration parameter (for example different tau for temperature sampling exploration). Since Ape-X, the industry realized that pre-allocating a massive, contiguous block of memory (a Tensor) and overwriting it in a circle is vastly superior for memory management and CPU caching (similar to what we do here in our implementation).

Something to note is that Ape-X strictly requires off-policy algorithms. Because data is generated by delayed networks using vastly different exploration parameters, on-policy algorithms (like standard PPO or A2C) would fail or suffer severe performance degradation in this architecture.

One thing to note there are some different ways of implementing distributed RL systems. This is one possible implementation. Some implementations also use a seperate process/node for the replay buffer, and seperate process/node for the shared parameter storage. This is especially true when using something like Ray for distributed computing.

NOTE: The original paper did not use a circular buffer for the replay buffer. It used a buffer with a "target" capacity, and allowed for overflow, every 100 steps it would flush the overflow from the buffer in a FIFO manner. This is in contrast to the implementation here which uses a circular buffer and doesn't allow for overflow. The paper used a key value buffer and so removed all old transitions at once and allowed for overflow of the buffer. We are using a circular buffer for simplicity, with our current pytorch based buffers, this would be inefficient.

NOTE: Our implementation uses ray which was not available at the time of the paper but is now widely used and makes the implementation much cleaner.

"""

# TODO: attempt a cleanup if possible

import os
import time
import ray
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import gymnasium as gym
import numpy as np
import random
import wandb
from tensordict import TensorDict
from functools import partial
from typing import Tuple, Dict, Any, Callable

from functional.replay_buffer import (
    init_per_buffer,
    sample_per,
    update_priorities,
    with_per_tracking,
    circular_write_strategy,
    make_n_step_accumulator,
)
from functional.losses import compute_q_td_loss, mse_loss, huber_loss
from functional.td import compute_q_td_target
from functional.action_selection import (
    argmax_selector,
)
from functional.schedules import get_ape_x_epsilon
from functional.optimizer import apply_gradients
from functional.network import hard_update_target_network, layer_init

# --- Constants ---
ENV_NAME = "CartPole-v1"
SEED = 42

BATCH_SIZE = 128
GAMMA = 0.99
LEARNING_RATE = 1e-3
BUFFER_CAPACITY = 50_000
MIN_BUFFER_SIZE = 5_000
TARGET_NET_UPDATE_FREQ = 100
MAX_LEARNER_STEPS = 30_000

# 0.2 and 1.0 because carpole is sensitive to bad and random moves
BASE_EPSILON = 0.2
EPSILON_ALPHA = 1.0

NUM_ACTORS = 4
ACTOR_BATCH_SIZE = 500

ALPHA = 0.6
BETA = 0.4
PREFETCH_COUNT = 3
N_STEP = 3
MAX_GRAD_NORM = 10.0


# Set seeds for all backends
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)


class DuelingDQN(nn.Module):
    def __init__(self, input_shape: Tuple, num_actions: int):
        super().__init__()
        self.l1 = layer_init(nn.Linear(input_shape[0], 512))
        self.value_head = layer_init(nn.Linear(512, 1), std=1.0)
        self.advantage_head = layer_init(nn.Linear(512, num_actions), std=1.0)

    def forward(self, x):
        x = F.relu(self.l1(x))
        v = self.value_head(x)
        a = self.advantage_head(x)
        return v + a - a.mean(dim=1, keepdim=True)


@ray.remote
class ReplayBufferActor:
    def __init__(self, capacity: int, shapes: Dict[str, Any]):
        self.buffer_state = init_per_buffer(capacity, shapes)
        # Tracking logic initialized once locally
        self.per_add = with_per_tracking(circular_write_strategy)

    def add_transitions(self, transitions: TensorDict):
        self.buffer_state = self.per_add(self.buffer_state, transitions)

    def sample_batch(
        self, batch_size: int, beta: float, min_size: int = 0
    ) -> Tuple[Any, torch.Tensor, torch.Tensor]:
        if self.buffer_state.size < min_size:
            return None, None, None
        beta_tensor = torch.tensor(beta, dtype=torch.float32)
        return sample_per(self.buffer_state, batch_size, beta_tensor)

    def update_priorities(
        self, tree_indices: torch.Tensor, td_errors: torch.Tensor, alpha: float
    ):
        self.buffer_state = update_priorities(
            self.buffer_state, tree_indices, td_errors, alpha
        )

    def get_info(self) -> Dict[str, Any]:
        return {"size": self.buffer_state.size}


@ray.remote
class ActorActor:
    def __init__(
        self,
        actor_id: int,
        num_actors: int,
        model_creator: Callable[[], nn.Module],
        selector_fn: Callable,
        target_fn: Callable,
        loss_fn: Callable,
        learner: ray.actor.ActorHandle,
        buffer: ray.actor.ActorHandle,
    ):
        self.actor_id = actor_id
        self.env = gym.make(ENV_NAME)
        self.env = gym.wrappers.RecordEpisodeStatistics(self.env)

        # Unique exploration rate per actor to ensure diverse experience
        self.epsilon = get_ape_x_epsilon(
            actor_id, num_actors, base_eps=BASE_EPSILON, alpha=EPSILON_ALPHA
        )

        self.learner = learner
        self.buffer = buffer

        # Instantiate models dynamically from the injected creator
        self.model = model_creator()
        self.target_model = model_creator()
        self.num_actions = self.env.action_space.n

        # Store functional dependencies
        self.selector_fn = selector_fn
        self.target_fn = target_fn
        self.loss_fn = loss_fn

        self.local_batch = []
        self.obs, _ = self.env.reset(seed=SEED + actor_id)
        self.step_count = 0
        self.n_step_proc, self.n_step_reset = make_n_step_accumulator(N_STEP, GAMMA)

        # Initial weight fetch
        self.weights_ref = self.learner.get_weights.remote()

        # Initialize W&B locally on the actor.
        # We use a group name to tie them all together in the W&B UI.
        wandb.init(
            project="ape-x-ray-cartpole",
            group="ape-x-distributed",
            job_type=f"actor_{actor_id}",
            config={"actor_id": actor_id, "epsilon": self.epsilon},
        )

    def run(self):
        while True:
            # 1. Non-blocking weight sync
            if self.weights_ref is not None:
                ready, _ = ray.wait([self.weights_ref], timeout=0)
                if ready:
                    weights = ray.get(self.weights_ref)
                    self.model.load_state_dict(weights)
                    self.target_model.load_state_dict(weights)
                    self.weights_ref = None

            # Only request new weights every 100 steps if no request is pending
            if self.weights_ref is None and self.step_count % 100 == 0:
                self.weights_ref = self.learner.get_weights.remote()

            # 2. Act
            with torch.inference_mode():
                obs_tensor = torch.as_tensor(self.obs[None, ...], dtype=torch.float32)

                # Manual epsilon-greedy
                predictions = self.model(obs_tensor)
                greedy_actions, _ = argmax_selector(predictions)

                if random.random() < self.epsilon:
                    action = random.randint(0, self.num_actions - 1)
                else:
                    action = greedy_actions.item()

            # 3. Step Env
            next_obs, reward, terminated, truncated, info = self.env.step(action)

            # 4. Compute N-step transitions
            n_step_transitions = self.n_step_proc(
                self.obs,
                action,
                reward,
                next_obs,
                terminated,
                truncated,
            )

            # 5. Accumulate transitions locally
            for n_step_td in n_step_transitions:
                self.local_batch.append(n_step_td)

            self.obs = next_obs
            self.step_count += 1

            # Handle Episode End
            if terminated or truncated:
                if "episode" in info:
                    wandb.log(
                        {
                            f"actor_{self.actor_id}/episode_return": info["episode"][
                                "r"
                            ][0],
                            f"actor_{self.actor_id}/episode_length": info["episode"][
                                "l"
                            ][0],
                            "global/episode_return": info["episode"]["r"][0],
                        },
                        step=self.step_count,
                    )
                self.obs, _ = self.env.reset()
                self.n_step_reset()

            # 6. Batched Priority Calculation and Push to remote buffer
            if len(self.local_batch) >= ACTOR_BATCH_SIZE:
                # Collate into a single batch
                collated = TensorDict(
                    {
                        k: torch.cat([t[k] for t in self.local_batch])
                        for k in self.local_batch[0].keys()
                    },
                    batch_size=[len(self.local_batch)],
                )
                # TODO: calling compute_q_td_loss leads to an extra forward pass to calculate priorities.
                # Compute Initial Priorities in one batched forward pass
                with torch.no_grad():
                    _, info_dict = compute_q_td_loss(
                        self.model,
                        collated,
                        self.target_model,
                        lambda obs, preds: argmax_selector(self.model(obs))[0],
                        partial(self.target_fn, gamma=collated["gamma"]),
                        loss_fn=self.loss_fn,
                    )

                collated["priority"] = info_dict["priorities"]

                # Push the prioritized batch to the buffer
                self.buffer.add_transitions.remote(collated)
                self.local_batch = []


@ray.remote(num_gpus=1 if torch.cuda.is_available() else 0)
class LearnerActor:
    def __init__(
        self,
        model_creator: Callable[[], nn.Module],
        selector_fn: Callable,
        target_fn: Callable,
        loss_fn: Callable,
        buffer: ray.actor.ActorHandle,
    ):
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        self.model = model_creator().to(self.device)
        self.target_model = model_creator().to(self.device)
        self.target_model.load_state_dict(self.model.state_dict())
        self.optimizer = optim.Adam(self.model.parameters(), lr=LEARNING_RATE)
        self.buffer = buffer

        # Store functional dependencies
        self.selector_fn = selector_fn
        self.target_fn = target_fn
        self.loss_fn = loss_fn
        self.step_count = 0
        self.prefetch_queue = []

        wandb.init(
            project="ape-x-ray-cartpole",
            group="ape-x-distributed",
            job_type="learner",
            config={
                "batch_size": BATCH_SIZE,
                "num_actors": NUM_ACTORS,
                "learning_rate": LEARNING_RATE,
                "gamma": GAMMA,
                "alpha": ALPHA,
                "beta": BETA,
            },
        )

    def get_weights(self) -> Dict[str, torch.Tensor]:
        return {k: v.cpu() for k, v in self.model.state_dict().items()}

    def step(self) -> Dict[str, Any]:
        # 1. Prime the queue if needed
        while len(self.prefetch_queue) < PREFETCH_COUNT:
            self.prefetch_queue.append(
                self.buffer.sample_batch.remote(BATCH_SIZE, BETA, MIN_BUFFER_SIZE)
            )

        # 2. Wait for at least one batch to be ready
        ready_refs, self.prefetch_queue = ray.wait(self.prefetch_queue, num_returns=1)
        result = ray.get(ready_refs[0])

        # 3. Handle the "buffer not ready" case
        if result[0] is None:
            # Maintain queue depth and return None
            self.prefetch_queue.append(
                self.buffer.sample_batch.remote(BATCH_SIZE, BETA, MIN_BUFFER_SIZE)
            )
            return None

        batch, indices, is_weights = result
        batch = batch.to(self.device)
        indices = indices.to(self.device)
        is_weights = is_weights.to(self.device)

        # Calculate Loss using injected functions
        loss, info = compute_q_td_loss(
            self.model,
            batch,
            self.target_model,
            lambda obs, preds: argmax_selector(self.model(obs))[0],
            partial(self.target_fn),
            loss_fn=self.loss_fn,
        )

        weighted_loss = (loss * is_weights).mean()
        self.optimizer = apply_gradients(
            self.optimizer,
            weighted_loss,
            model=self.model,
            clip_grad_norm=MAX_GRAD_NORM,
        )

        # Update Priorities
        td_errors = info["priorities"].detach().cpu()
        self.buffer.update_priorities.remote(indices.cpu(), td_errors, ALPHA)

        self.step_count += 1
        if self.step_count % TARGET_NET_UPDATE_FREQ == 0:
            hard_update_target_network(self.model, self.target_model)

        metrics = {
            "learner/loss": weighted_loss.item(),
            "learner/mean_q": info["q_values/mean"],
        }
        wandb.log(metrics, step=self.step_count)
        return metrics


def main():
    ray.init()

    # 1. Warm up environment to suppress gymnasium registry warnings
    temp_env = gym.make(ENV_NAME)
    obs_shape = temp_env.observation_space.shape
    num_actions = temp_env.action_space.n
    temp_env.reset()
    temp_env.close()

    # 2. Define the Algorithm Components (Transparent and Reusable)
    my_model_creator = lambda: DuelingDQN(obs_shape, num_actions)
    my_selector_fn = argmax_selector
    my_target_fn = compute_q_td_target
    my_loss_fn = huber_loss

    # 3. Initialize Buffer
    buffer_shapes = {
        "obs": obs_shape,
        "action": (),
        "reward": (),
        "terminated": (),
        "truncated": (),
        "next_obs": obs_shape,
        "gamma": (),
        "priority": (),
    }
    buffer = ReplayBufferActor.remote(BUFFER_CAPACITY, buffer_shapes)

    # 4. Initialize Learner with Functional Logic
    learner = LearnerActor.remote(
        model_creator=my_model_creator,
        selector_fn=my_selector_fn,
        target_fn=my_target_fn,
        loss_fn=my_loss_fn,
        buffer=buffer,
    )

    # 5. Initialize Actors with Functional Logic
    actors = [
        ActorActor.remote(
            actor_id=i,
            num_actors=NUM_ACTORS,
            model_creator=my_model_creator,
            selector_fn=my_selector_fn,
            target_fn=my_target_fn,
            loss_fn=my_loss_fn,
            learner=learner,
            buffer=buffer,
        )
        for i in range(NUM_ACTORS)
    ]

    for actor in actors:
        actor.run.remote()

    print("Starting training loop...")
    try:
        for step in range(MAX_LEARNER_STEPS):
            metrics = ray.get(learner.step.remote())
            if metrics and step % 100 == 0:
                print(f"Step {step}: Loss={metrics['learner/loss']:.4f}")
            elif not metrics:
                time.sleep(0.5)
    except KeyboardInterrupt:
        print("Training interrupted.")
    finally:
        ray.shutdown()


if __name__ == "__main__":
    main()
